"""Tiny, bounded group mechanics for validation lessons.

This module is intentionally non-secure.  Its parameters are public, tiny,
and fixed so every value can be enumerated.  It demonstrates validation order
and agreement mechanics only.  It does not implement encryption, signatures,
a KEM, a protocol, or production Diffie-Hellman.
"""

from __future__ import annotations


TOY_PRIME = 23
TOY_SUBGROUP_ORDER = 11
TOY_GENERATOR = 2
MIN_TOY_SCALAR = 1
MAX_TOY_SCALAR = TOY_SUBGROUP_ORDER - 1


def _require_exact_int(value: object, name: str) -> int:
    if type(value) is not int:
        raise TypeError(f"{name} must be an exact integer")
    return value


def validate_toy_scalar(value: object) -> int:
    """Return a bounded teaching scalar after exact validation."""

    scalar = _require_exact_int(value, "toy scalar")
    if not MIN_TOY_SCALAR <= scalar <= MAX_TOY_SCALAR:
        raise ValueError(
            f"toy scalar must be in {MIN_TOY_SCALAR}..{MAX_TOY_SCALAR}"
        )
    return scalar


def validate_toy_public(value: object) -> int:
    """Validate a non-identity member of the fixed order-11 subgroup."""

    public_value = _require_exact_int(value, "toy public value")
    if not 2 <= public_value <= TOY_PRIME - 2:
        raise ValueError("toy public value is outside the accepted range")
    if pow(public_value, TOY_SUBGROUP_ORDER, TOY_PRIME) != 1:
        raise ValueError("toy public value is not in the fixed subgroup")
    return public_value


def toy_public_value(scalar: object) -> int:
    """Map a validated teaching scalar to a public subgroup value."""

    checked_scalar = validate_toy_scalar(scalar)
    result = pow(TOY_GENERATOR, checked_scalar, TOY_PRIME)
    return validate_toy_public(result)


def toy_agreement_value(local_scalar: object, peer_public: object) -> int:
    """Return a public teaching result after validating both inputs.

    The result is deliberately not a secret: the entire state space has only
    eleven elements and is suitable only for bounded classroom inspection.
    """

    checked_scalar = validate_toy_scalar(local_scalar)
    checked_peer = validate_toy_public(peer_public)
    result = pow(checked_peer, checked_scalar, TOY_PRIME)
    return validate_toy_public(result)


def enumerate_toy_subgroup() -> tuple[int, ...]:
    """Return every element generated by the fixed teaching profile."""

    return tuple(
        pow(TOY_GENERATOR, exponent, TOY_PRIME)
        for exponent in range(TOY_SUBGROUP_ORDER)
    )


assert pow(TOY_GENERATOR, TOY_SUBGROUP_ORDER, TOY_PRIME) == 1
assert len(set(enumerate_toy_subgroup())) == TOY_SUBGROUP_ORDER
